# Generated by Django 4.0.5 on 2022-06-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='núm_pag',
            new_name='número_pagina',
        ),
    ]
