# Generated by Django 4.0.4 on 2022-06-01 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localización', models.CharField(max_length=60, verbose_name='Localización')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro', verbose_name='Título del libro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('dirección', models.CharField(max_length=80, verbose_name='Dirección')),
                ('teléfono', models.BigIntegerField(verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dev', models.DateField(verbose_name='Fecha de Devolución')),
                ('fecha_pres', models.DateField(verbose_name='Fecha de Préstamo')),
                ('ejemplar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ejemplares.ejemplares', verbose_name='Ejemplar')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ejemplares.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='ejemplares',
            name='usuario',
            field=models.ManyToManyField(through='ejemplares.Prestamo', to='ejemplares.usuario'),
        ),
    ]
